site_name: Retro.I - Docs

site_url: https://docs.retroi.de/
repo_url: https://github.com/Retro-i/Retro.I
repo_name: Retro.I

copyright: <div class="md-copyright">Made with &#10084; and <b><a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a></b> by <b><a href="https://github.com/DomeRepo">@DomeRepo</a></b> and <b><a href="https://github.com/felixholfelder">@felixholfelder</a></b></div>

nav:
  - Home: 
      - index.md

  - Projektdokumentation:
      - projectdocumentation/index.md
      - Vorher Nachher: projectdocumentation/vorher_nachher.md
      - Entkernung: projectdocumentation/entkernung.md
      - Gehäuse - Touchdisplay: projectdocumentation/gehaeuse.md
      - Einbau Lautsprecher: projectdocumentation/lautsprecher.md
      - LED-Streifen: projectdocumentation/led_streifen.md
      - Dreh-Impulsgeber: projectdocumentation/dreh_impulsgeber.md
      - Schaltplan: projectdocumentation/schaltplan.md
      - Zusammenbau: projectdocumentation/zusammenbau.md
      - Fertiger Retro.I: projectdocumentation/fertiger_retroI.md

  - Benutzerhandbuch:
      - user-manual/index.md
        # Vorwort + Übersicht + Inhaltsverzeichnis?
      - Menführung: 
        # Übersicht, Menüführung, Erklärung der Icons, z. B. Design wechsel, WLAN, Bluetooth
        - Lautstärke, Stummschalten & Equalizer: user-manual/Startbildschirm.md
        - System Ein- und Ausschalten: user-manual/on-off.md
        # Symbolführung 
        - Darkmode / Lightmode: user-manual/dark_light.md 
        # Einschalten / Ausschalten, Auswählen, Passwort eingabe, Symbolführung
        - W-LAN / LAN: user-manual/WLAN.md 
        # Einschalten / Ausschalten, Auswählen, Passwort eingabe, Symbolführung
      - Radiosender: user-manual/radiosender.md
        # Radiosender auswahl + Sendersuche + Hinzufügen von neuen Radiosendern / lösche
      - Bluetooth: user-manual/Bluetooth.md
        # aktivieren + Verbindungen + Namen ändern, Symbolführung
      - Einstellungen: 
        # NUR Symbolführung, Überpunkt hinter welchem Symbol steckt was
      # Frage ist hier ob App, Updates, Logs ausgeblendet werden oder nicht.
        - Audio: user-manual/audio.md
          # Lautstärke + Stummschalten + Erklärung mit Drehimpulsgeber
        - Anzeige: user-manual/anzeige.md
          # Symbolführung 
        - LED-Streifen: user-manual/led-streifen.md
          # Symbolführung
        - Infos: user-manual/infos.md
        # CPU Temperatur, Netzwerkinfos, Credits, 
      - GPO-PIN-Belegung / Schaltplan: user-manual/PIN-Belegung.md
        # Schaubild Pin Belegung + Tabelle
        
  - Setup:
      - setup/index.md
      - Systemeinrichtung: setup/systemeinrichtung.md
      - App-Einrichtung: setup/app-einrichtung.md
      - Zusätzliche Hinweise: setup/hinweise.md

  - Changelog:
      - changelog/index.md

extra:
  generator: false

theme:
  name: material
  favicon: assets/retroi_icon.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Auf Lightmode umschalten

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Auf Darkmode umschalten

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Auf Systemstandard umschalten
  language: de
  icon:
    repo: fontawesome/brands/github
    logo: material/radio
  features:
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.share
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.tabs
    - navigation.top

plugins:
    - mkdocs_github_changelog
    - optimize

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.escapeall:
      hardbreak: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
  # Annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
